sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t akovalenko/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akovalenko/docker-react npm run test